site: STATMIKE

url: https://statmike.com
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: statmike
      commenting: open
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: statmike
      commenting: open

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

google_analytics: UA-151604211-1

emptyArray: []

comments:
 receiver: https://jekyllcommenting.azurewebsites.net/api/PostComment

authors:
 statmike:
   name: statmike
   email: statmike@gmail.com
   url: https://statmike.com
